//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csizmazia.WpfDynamicUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csizmazia.WpfDynamicUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the about form.
        /// </summary>
        public static string AboutApplicationDescription {
            get {
                return ResourceManager.GetString("AboutApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutApplicationName {
            get {
                return ResourceManager.GetString("AboutApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaging language of the application.
        /// </summary>
        public static string ChangeLanguageDescription {
            get {
                return ResourceManager.GetString("ChangeLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguageName {
            get {
                return ResourceManager.GetString("ChangeLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to close this form and return to previous form.
        /// </summary>
        public static string CloseDescription {
            get {
                return ResourceManager.GetString("CloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseName {
            get {
                return ResourceManager.GetString("CloseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string ComponentsName {
            get {
                return ResourceManager.GetString("ComponentsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The culture has been changed to {0}..
        /// </summary>
        public static string CultureInfoChanged {
            get {
                return ResourceManager.GetString("CultureInfoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultures.
        /// </summary>
        public static string CulturesName {
            get {
                return ResourceManager.GetString("CulturesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the current page.
        /// </summary>
        public static string CurrentPageDescription {
            get {
                return ResourceManager.GetString("CurrentPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page.
        /// </summary>
        public static string CurrentPageName {
            get {
                return ResourceManager.GetString("CurrentPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionName {
            get {
                return ResourceManager.GetString("DescriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for displayed name.
        /// </summary>
        public static string FilterCultureDisplayNameDescription {
            get {
                return ResourceManager.GetString("FilterCultureDisplayNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture display name filter.
        /// </summary>
        public static string FilterCultureDisplayNameName {
            get {
                return ResourceManager.GetString("FilterCultureDisplayNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter display name to filter.
        /// </summary>
        public static string FilterCultureDisplayNamePrompt {
            get {
                return ResourceManager.GetString("FilterCultureDisplayNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for english name.
        /// </summary>
        public static string FilterCultureEnglishNameDescription {
            get {
                return ResourceManager.GetString("FilterCultureEnglishNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture english name.
        /// </summary>
        public static string FilterCultureEnglishNameName {
            get {
                return ResourceManager.GetString("FilterCultureEnglishNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for english name.
        /// </summary>
        public static string FilterCultureEnglishNamePrompt {
            get {
                return ResourceManager.GetString("FilterCultureEnglishNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture name filter.
        /// </summary>
        public static string FilterCultureNameName {
            get {
                return ResourceManager.GetString("FilterCultureNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter to filter culture name.
        /// </summary>
        public static string FilterCultureNamePrompt {
            get {
                return ResourceManager.GetString("FilterCultureNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for native name.
        /// </summary>
        public static string FilterCultureNativeNameDescription {
            get {
                return ResourceManager.GetString("FilterCultureNativeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture native name.
        /// </summary>
        public static string FilterCultureNativeNameName {
            get {
                return ResourceManager.GetString("FilterCultureNativeNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter native name to filter.
        /// </summary>
        public static string FilterCultureNativeNamePrompt {
            get {
                return ResourceManager.GetString("FilterCultureNativeNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for system name.
        /// </summary>
        public static string FilterCultureSystemNameDescription {
            get {
                return ResourceManager.GetString("FilterCultureSystemNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture system name.
        /// </summary>
        public static string FilterCultureSystemNameName {
            get {
                return ResourceManager.GetString("FilterCultureSystemNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter system name to filter.
        /// </summary>
        public static string FilterCultureSystemNamePrompt {
            get {
                return ResourceManager.GetString("FilterCultureSystemNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes the extension cache.
        /// </summary>
        public static string InitializeExtensionCacheDescription {
            get {
                return ResourceManager.GetString("InitializeExtensionCacheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize cache.
        /// </summary>
        public static string InitializeExtensionCacheName {
            get {
                return ResourceManager.GetString("InitializeExtensionCacheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2008-2011 Universe, WARNING: This software can access some map providers and may viotile their Terms of Service, you use it at your own risk, nothing is forcing you to accept this ;} Source itself is legal!
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseMIT {
            get {
                return ResourceManager.GetString("LicenseMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///
        ///A &quot;contributor&quot; is any person that distributes its contribution [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseMs_PL {
            get {
                return ResourceManager.GetString("LicenseMs_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseName {
            get {
                return ResourceManager.GetString("LicenseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to the system.
        /// </summary>
        public static string LoginDescription {
            get {
                return ResourceManager.GetString("LoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the first page.
        /// </summary>
        public static string MoveFirstDescription {
            get {
                return ResourceManager.GetString("MoveFirstDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string MoveFirstName {
            get {
                return ResourceManager.GetString("MoveFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the last page.
        /// </summary>
        public static string MoveLastDescription {
            get {
                return ResourceManager.GetString("MoveLastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string MoveLastName {
            get {
                return ResourceManager.GetString("MoveLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the next page.
        /// </summary>
        public static string MoveNextDescription {
            get {
                return ResourceManager.GetString("MoveNextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string MoveNextName {
            get {
                return ResourceManager.GetString("MoveNextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the previous page.
        /// </summary>
        public static string MovePreviousDescription {
            get {
                return ResourceManager.GetString("MovePreviousDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string MovePreviousName {
            get {
                return ResourceManager.GetString("MovePreviousName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameName {
            get {
                return ResourceManager.GetString("NameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the number of pages.
        /// </summary>
        public static string PageCountDescription {
            get {
                return ResourceManager.GetString("PageCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page count.
        /// </summary>
        public static string PageCountName {
            get {
                return ResourceManager.GetString("PageCountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        public static string PageSizeDescription {
            get {
                return ResourceManager.GetString("PageSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        public static string PageSizeName {
            get {
                return ResourceManager.GetString("PageSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloads the collection.
        /// </summary>
        public static string ReloadDescription {
            get {
                return ResourceManager.GetString("ReloadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ReloadName {
            get {
                return ResourceManager.GetString("ReloadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the collection.
        /// </summary>
        public static string ResetDesciption {
            get {
                return ResourceManager.GetString("ResetDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetName {
            get {
                return ResourceManager.GetString("ResetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected culture.
        /// </summary>
        public static string SelectedCulturesItem {
            get {
                return ResourceManager.GetString("SelectedCulturesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string UrlName {
            get {
                return ResourceManager.GetString("UrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use language.
        /// </summary>
        public static string UseLanguageName {
            get {
                return ResourceManager.GetString("UseLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome message.
        /// </summary>
        public static string WelcomeMessageName {
            get {
                return ResourceManager.GetString("WelcomeMessageName", resourceCulture);
            }
        }
    }
}
