//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Csizmazia.WpfDynamicEntity.Data
{
    public partial class Shippers
    {
        public Shippers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Shipper_ID { get; set; }
        public string Company_Name { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
    
}
